/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Color;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import login_ragister_design.jdbc;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author PrajitGyawali
 */
public class AdminPortal extends javax.swing.JFrame {

    static boolean maximize = true;
    int x;
    int y;
    public AdminPortal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        ButtonExit = new javax.swing.JButton();
        ButtonMinimize = new javax.swing.JButton();
        ButtonMaximize1 = new javax.swing.JButton();
        PanelAdmin = new javax.swing.JPanel();
        labelQN = new javax.swing.JLabel();
        labelAdminIcon = new javax.swing.JLabel();
        labelWelcome = new javax.swing.JLabel();
        labelAvailable = new javax.swing.JLabel();
        labelConcert = new javax.swing.JLabel();
        labelInvoice = new javax.swing.JLabel();
        labelBookings = new javax.swing.JLabel();
        labelview = new javax.swing.JLabel();
        buttonView = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        labelLogOut = new javax.swing.JLabel();
        buttonConcert = new javax.swing.JButton();
        buttonBookings = new javax.swing.JButton();
        buttonInvoice = new javax.swing.JButton();
        buttonAvailable = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();
        panelAvailable = new javax.swing.JPanel();
        labelNowAvailablepnl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelEdit = new javax.swing.JPanel();
        labelViewandEditpnl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelConcert = new javax.swing.JPanel();
        labelManageConcertpnl = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        panelBookings = new javax.swing.JPanel();
        labelManageBookingsPanel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        panelInvoice = new javax.swing.JPanel();
        labelInvoicepnl = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setUndecorated(true);
        setSize(new java.awt.Dimension(880, 544));

        panelHeader.setBackground(new java.awt.Color(204, 204, 204));
        panelHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelHeaderMouseDragged(evt);
            }
        });
        panelHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelHeaderMousePressed(evt);
            }
        });

        ButtonExit.setBackground(new java.awt.Color(255, 255, 255));
        ButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-delete-filled-50.png"))); // NOI18N
        ButtonExit.setContentAreaFilled(false);
        ButtonExit.setOpaque(true);
        ButtonExit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-delete-48.png"))); // NOI18N
        ButtonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonExitMouseExited(evt);
            }
        });

        ButtonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-minimize-window-50.png"))); // NOI18N
        ButtonMinimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-minimize-window-30.png"))); // NOI18N
        ButtonMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonMinimizeMouseExited(evt);
            }
        });
        ButtonMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinimizeActionPerformed(evt);
            }
        });

        ButtonMaximize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-maximize-window-50.png"))); // NOI18N
        ButtonMaximize1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-maximize-window-30.png"))); // NOI18N
        ButtonMaximize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMaximize1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonMaximize1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonMaximize1MouseExited(evt);
            }
        });
        ButtonMaximize1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMaximize1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ButtonMaximize1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addComponent(ButtonMaximize1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelAdmin.setBackground(new java.awt.Color(255, 255, 255));
        PanelAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelQN.setBackground(new java.awt.Color(0, 0, 0));
        labelQN.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        labelQN.setText("Do you want to Logout ?");
        labelQN.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        PanelAdmin.add(labelQN, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, 25));

        labelAdminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-admin-settings-male-filled-100.png"))); // NOI18N
        PanelAdmin.add(labelAdminIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 111, 133));

        labelWelcome.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        labelWelcome.setText("Welcome  Admin !!");
        PanelAdmin.add(labelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 345, 51));

        labelAvailable.setBackground(new java.awt.Color(0, 0, 0));
        labelAvailable.setOpaque(true);
        PanelAdmin.add(labelAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 130, 9));

        labelConcert.setBackground(new java.awt.Color(255, 255, 255));
        labelConcert.setOpaque(true);
        PanelAdmin.add(labelConcert, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 140, 9));

        labelInvoice.setBackground(new java.awt.Color(255, 255, 255));
        labelInvoice.setOpaque(true);
        PanelAdmin.add(labelInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 160, 9));

        labelBookings.setBackground(new java.awt.Color(255, 255, 255));
        labelBookings.setOpaque(true);
        PanelAdmin.add(labelBookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 150, 9));

        labelview.setBackground(new java.awt.Color(255, 255, 255));
        labelview.setOpaque(true);
        PanelAdmin.add(labelview, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 110, 9));

        buttonView.setBackground(new java.awt.Color(255, 255, 255));
        buttonView.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonView.setText("View/Edit");
        buttonView.setContentAreaFilled(false);
        buttonView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });
        PanelAdmin.add(buttonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 130, 30));

        labelLogOut.setForeground(new java.awt.Color(0, 102, 204));
        labelLogOut.setText(" LogOut");
        labelLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLogOutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(labelLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(labelLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        PanelAdmin.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, -20, -1, -1));

        buttonConcert.setBackground(new java.awt.Color(255, 255, 255));
        buttonConcert.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonConcert.setText("Manage Concerts");
        buttonConcert.setContentAreaFilled(false);
        buttonConcert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonConcert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConcertActionPerformed(evt);
            }
        });
        PanelAdmin.add(buttonConcert, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 30));

        buttonBookings.setBackground(new java.awt.Color(255, 255, 255));
        buttonBookings.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonBookings.setText("Manage Bookings");
        buttonBookings.setContentAreaFilled(false);
        buttonBookings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBookingsActionPerformed(evt);
            }
        });
        PanelAdmin.add(buttonBookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 180, 30));

        buttonInvoice.setBackground(new java.awt.Color(255, 255, 255));
        buttonInvoice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonInvoice.setText("Generate Invoice");
        buttonInvoice.setContentAreaFilled(false);
        buttonInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInvoiceActionPerformed(evt);
            }
        });
        PanelAdmin.add(buttonInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 180, 30));

        buttonAvailable.setBackground(new java.awt.Color(255, 255, 255));
        buttonAvailable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonAvailable.setText("Available");
        buttonAvailable.setContentAreaFilled(false);
        buttonAvailable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAvailableActionPerformed(evt);
            }
        });
        PanelAdmin.add(buttonAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 130, 30));

        panelContent.setBackground(new java.awt.Color(204, 204, 204));
        panelContent.setLayout(new java.awt.CardLayout());

        labelNowAvailablepnl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNowAvailablepnl.setText("Now Available");

        javax.swing.GroupLayout panelAvailableLayout = new javax.swing.GroupLayout(panelAvailable);
        panelAvailable.setLayout(panelAvailableLayout);
        panelAvailableLayout.setHorizontalGroup(
            panelAvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvailableLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelAvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNowAvailablepnl, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        panelAvailableLayout.setVerticalGroup(
            panelAvailableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAvailableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNowAvailablepnl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
        );

        panelContent.add(panelAvailable, "card2");

        labelViewandEditpnl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelViewandEditpnl.setText("View and Edit");

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "S. No", "First Name", "Last Name", "Gender", "Phone No.", "E-mail", "Address", "Town", "Post Code", "Contact Name", "Web Address", "Account No.", "Payment Method"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Search");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEditLayout = new javax.swing.GroupLayout(panelEdit);
        panelEdit.setLayout(panelEditLayout);
        panelEditLayout.setHorizontalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(panelEditLayout.createSequentialGroup()
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEditLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelViewandEditpnl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEditLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        panelEditLayout.setVerticalGroup(
            panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelEditLayout.createSequentialGroup()
                        .addComponent(labelViewandEditpnl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEditLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panelEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(jButton2))
        );

        panelContent.add(panelEdit, "card3");

        labelManageConcertpnl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelManageConcertpnl.setText("Manage Concert");

        javax.swing.GroupLayout panelConcertLayout = new javax.swing.GroupLayout(panelConcert);
        panelConcert.setLayout(panelConcertLayout);
        panelConcertLayout.setHorizontalGroup(
            panelConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConcertLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelManageConcertpnl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        panelConcertLayout.setVerticalGroup(
            panelConcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConcertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageConcertpnl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        panelContent.add(panelConcert, "card4");

        labelManageBookingsPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelManageBookingsPanel.setText("Manage Bookings");

        javax.swing.GroupLayout panelBookingsLayout = new javax.swing.GroupLayout(panelBookings);
        panelBookings.setLayout(panelBookingsLayout);
        panelBookingsLayout.setHorizontalGroup(
            panelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBookingsLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelManageBookingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        panelBookingsLayout.setVerticalGroup(
            panelBookingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBookingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelManageBookingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(360, Short.MAX_VALUE))
        );

        panelContent.add(panelBookings, "card5");

        labelInvoicepnl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelInvoicepnl.setText("Generate Invoice");

        javax.swing.GroupLayout panelInvoiceLayout = new javax.swing.GroupLayout(panelInvoice);
        panelInvoice.setLayout(panelInvoiceLayout);
        panelInvoiceLayout.setHorizontalGroup(
            panelInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvoiceLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInvoiceLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelInvoicepnl, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        panelInvoiceLayout.setVerticalGroup(
            panelInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInvoicepnl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        panelContent.add(panelInvoice, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(PanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1083, 661));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinimizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonMinimizeActionPerformed

    private void ButtonMaximize1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMaximize1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonMaximize1ActionPerformed

    private void ButtonExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExitMouseEntered
        ButtonExit.setBackground( new Color(255,255,255));
    }//GEN-LAST:event_ButtonExitMouseEntered

    private void ButtonExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExitMouseExited
        ButtonExit.setBackground( new Color(255,255,255));
    }//GEN-LAST:event_ButtonExitMouseExited

    private void ButtonMaximize1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMaximize1MouseEntered
     ButtonMaximize1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_ButtonMaximize1MouseEntered

    private void ButtonMaximize1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMaximize1MouseExited
     ButtonMaximize1.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_ButtonMaximize1MouseExited

    private void ButtonMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMinimizeMouseEntered
    ButtonMinimize.setBackground( new Color(255,255,255));
    }//GEN-LAST:event_ButtonMinimizeMouseEntered

    private void ButtonMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMinimizeMouseExited
    ButtonMinimize.setBackground( new Color(0,0,0));
    
    }//GEN-LAST:event_ButtonMinimizeMouseExited

    private void ButtonExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonExitMouseClicked
    System.exit(0);
    }//GEN-LAST:event_ButtonExitMouseClicked

    private void ButtonMaximize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMaximize1MouseClicked
    if (maximize){
        AdminPortal.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        maximize =  false;
    }
    else{
            setExtendedState(JFrame.NORMAL);
                maximize = true;
    }
    }//GEN-LAST:event_ButtonMaximize1MouseClicked

    private void ButtonMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMinimizeMouseClicked
    this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_ButtonMinimizeMouseClicked

    private void panelHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMousePressed
    x = evt.getX();
    y = evt.getY();
    }//GEN-LAST:event_panelHeaderMousePressed

    private void panelHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelHeaderMouseDragged
    if(maximize) {
        int a =evt.getXOnScreen();
        int b = evt.getYOnScreen();
        this.setLocation(a -x,b -y);
        
        
    }
    }//GEN-LAST:event_panelHeaderMouseDragged

    private void buttonAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAvailableActionPerformed
      labelAvailable.setBackground(new Color(0,0,0));
      
      labelview.setBackground( new Color(255,255,255));
      labelConcert.setBackground( new Color(255,255,255));
      labelBookings.setBackground( new Color(255,255,255));
      labelInvoice.setBackground( new Color(255,255,255));
      
      panelContent.removeAll();
        panelContent.repaint();
        panelContent.revalidate();
        panelContent.add(panelAvailable);
        panelContent.repaint();
        panelContent.revalidate();
      
    }//GEN-LAST:event_buttonAvailableActionPerformed

    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
    
      labelAvailable.setBackground(new Color(255,255,255));
      labelview.setBackground( new Color(0,0,0));
      labelConcert.setBackground( new Color(255,255,255));
      labelBookings.setBackground( new Color(255,255,255));
      labelInvoice.setBackground( new Color(255,255,255));
      
      
        panelContent.removeAll();
        panelContent.repaint();
        panelContent.revalidate();
        panelContent.add(panelEdit);
        panelContent.repaint();
        panelContent.revalidate();
        fetch();
      
    }//GEN-LAST:event_buttonViewActionPerformed

    private void buttonConcertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConcertActionPerformed
    labelAvailable.setBackground(new Color(255,255,255));
      labelview.setBackground( new Color(255,255,255));
      labelConcert.setBackground( new Color(0,0,0));
      labelBookings.setBackground( new Color(255,255,255));
      labelInvoice.setBackground( new Color(255,255,255));
      
        panelContent.removeAll();
        panelContent.repaint();
        panelContent.revalidate();
        panelContent.add(panelConcert);
        panelContent.repaint();
        panelContent.revalidate();
        
    }//GEN-LAST:event_buttonConcertActionPerformed

    private void buttonBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBookingsActionPerformed
        labelAvailable.setBackground(new Color(255,255,255));
        labelview.setBackground( new Color(255,255,255));
        labelConcert.setBackground( new Color(255,255,255));
        labelBookings.setBackground( new Color(0,0,0));
        labelInvoice.setBackground( new Color(255,255,255));
        
        panelContent.removeAll();
        panelContent.repaint();
        panelContent.revalidate();
        panelContent.add(panelBookings);
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_buttonBookingsActionPerformed

    private void buttonInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInvoiceActionPerformed
        labelAvailable.setBackground(new Color(255,255,255));
        labelview.setBackground( new Color(255,255,255));
        labelConcert.setBackground( new Color(255,255,255));
        labelBookings.setBackground( new Color(255,255,255));
        labelInvoice.setBackground( new Color(0,0,0));
        
        panelContent.removeAll();
        panelContent.repaint();
        panelContent.revalidate();
        panelContent.add(panelInvoice);
        panelContent.repaint();
        panelContent.revalidate();
    }//GEN-LAST:event_buttonInvoiceActionPerformed

    private void labelLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogOutMouseClicked
        admin log = new admin();
        log.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_labelLogOutMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        registration1 lo = new registration1();
        lo.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
    }//GEN-LAST:event_jTable1MouseClicked
    public ArrayList<User> ListUsers(String ValToSearch)
    {
        ArrayList<User> usersList = new ArrayList<User>();
        
        PreparedStatement st;
        ResultSet rs;
        
        try{
            String searchQuery = "SELECT * FROM `userinfo`";
            st=jdbc.getConnection().prepareStatement(searchQuery);
            
            rs = st.executeQuery(searchQuery);
            
            User user;
            
            while(rs.next())
            {
                user = new User(
                                 rs.getInt("id"),
                                 rs.getString("fname"),
                                 rs.getString("lname"),
                                 rs.getInt("age")
                                );
                usersList.add(user);
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return usersList;
    }
    
    
    
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
        String search=jTextField1.getText().toLowerCase();
        TableRowSorter<DefaultTablemodel> tr= new TableRowSorter<DefaultTableModel>(table);
    }//GEN-LAST:event_jTextField1KeyReleased

    public void fetch(){
    try{
        String q ="select * from userinfo";
        PreparedStatement st;
        ResultSet rs;
        
        st = jdbc.getConnection().prepareStatement(q);
                
        rs = st.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                
    
    
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    
    }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonMaximize1;
    private javax.swing.JButton ButtonMinimize;
    private javax.swing.JPanel PanelAdmin;
    private javax.swing.JButton buttonAvailable;
    private javax.swing.JButton buttonBookings;
    private javax.swing.JButton buttonConcert;
    private javax.swing.JButton buttonInvoice;
    private javax.swing.JButton buttonView;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelAdminIcon;
    private javax.swing.JLabel labelAvailable;
    private javax.swing.JLabel labelBookings;
    private javax.swing.JLabel labelConcert;
    private javax.swing.JLabel labelInvoice;
    private javax.swing.JLabel labelInvoicepnl;
    private javax.swing.JLabel labelLogOut;
    private javax.swing.JLabel labelManageBookingsPanel;
    private javax.swing.JLabel labelManageConcertpnl;
    private javax.swing.JLabel labelNowAvailablepnl;
    private javax.swing.JLabel labelQN;
    private javax.swing.JLabel labelViewandEditpnl;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JLabel labelview;
    private java.awt.Panel panel1;
    private javax.swing.JPanel panelAvailable;
    private javax.swing.JPanel panelBookings;
    private javax.swing.JPanel panelConcert;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelEdit;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelInvoice;
    // End of variables declaration//GEN-END:variables
}
