/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.*;
import java.sql.PreparedStatement;
import javax.swing.*;
import login_ragister_design.jdbc;


/**
 *
 * @author PrajitGyawali
 */
public class CustomerDashboard extends javax.swing.JFrame {

    static boolean max = true;
    int xmouse;
    int ymouse;
    int uid = 0;
    private Object jTextField8;
    public CustomerDashboard() {
        initComponents();
    }
    
    public void setCurrentUserId(int userid){
        uid = userid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustomerHeader = new java.awt.Panel();
        BtnExitCustomer = new javax.swing.JButton();
        ButtonMaximizeCus = new javax.swing.JButton();
        ButtonMinimizeCus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonCustomerConceret = new javax.swing.JButton();
        buttonCustomerView = new javax.swing.JButton();
        buttonBookConceret = new javax.swing.JButton();
        buttonCustomerConcerts = new javax.swing.JButton();
        panelCustomer = new javax.swing.JPanel();
        panelcustomerconcert = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        panelcustomerbooking = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panelcustomeredit = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        panelcustomerview = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelCustomerHeader.setBackground(new java.awt.Color(204, 204, 204));
        panelCustomerHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCustomerHeaderMousePressed(evt);
            }
        });
        panelCustomerHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelCustomerHeaderMouseDragged(evt);
            }
        });

        BtnExitCustomer.setBackground(new java.awt.Color(255, 255, 255));
        BtnExitCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconAdmin/icons8-delete-filled-50.png"))); // NOI18N
        BtnExitCustomer.setContentAreaFilled(false);
        BtnExitCustomer.setOpaque(true);
        BtnExitCustomer.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconAdmin/icons8-delete-48.png"))); // NOI18N
        BtnExitCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnExitCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnExitCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnExitCustomerMouseExited(evt);
            }
        });

        ButtonMaximizeCus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconAdmin/icons8-maximize-window-50.png"))); // NOI18N
        ButtonMaximizeCus.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconAdmin/icons8-maximize-window-30.png"))); // NOI18N
        ButtonMaximizeCus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMaximizeCusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonMaximizeCusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonMaximizeCusMouseExited(evt);
            }
        });
        ButtonMaximizeCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMaximizeCusActionPerformed(evt);
            }
        });

        ButtonMinimizeCus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconAdmin/icons8-minimize-window-50.png"))); // NOI18N
        ButtonMinimizeCus.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/IconAdmin/icons8-minimize-window-30.png"))); // NOI18N
        ButtonMinimizeCus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMinimizeCusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonMinimizeCusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonMinimizeCusMouseExited(evt);
            }
        });
        ButtonMinimizeCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMinimizeCusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCustomerHeaderLayout = new javax.swing.GroupLayout(panelCustomerHeader);
        panelCustomerHeader.setLayout(panelCustomerHeaderLayout);
        panelCustomerHeaderLayout.setHorizontalGroup(
            panelCustomerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomerHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonMinimizeCus, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ButtonMaximizeCus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnExitCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCustomerHeaderLayout.setVerticalGroup(
            panelCustomerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerHeaderLayout.createSequentialGroup()
                .addGroup(panelCustomerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnExitCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMaximizeCus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonMinimizeCus, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconCustomer/note-128.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("Welcome to Music World !!");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Do you want to LogOut,");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Logout");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        buttonCustomerConceret.setBackground(new java.awt.Color(255, 255, 255));
        buttonCustomerConceret.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonCustomerConceret.setText("Edit Info");
        buttonCustomerConceret.setContentAreaFilled(false);
        buttonCustomerConceret.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCustomerConceret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerConceretActionPerformed(evt);
            }
        });

        buttonCustomerView.setBackground(new java.awt.Color(255, 255, 255));
        buttonCustomerView.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonCustomerView.setText(" View Booking");
        buttonCustomerView.setContentAreaFilled(false);
        buttonCustomerView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCustomerView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerViewActionPerformed(evt);
            }
        });

        buttonBookConceret.setBackground(new java.awt.Color(255, 255, 255));
        buttonBookConceret.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonBookConceret.setText("Bookings");
        buttonBookConceret.setContentAreaFilled(false);
        buttonBookConceret.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonBookConceret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBookConceretActionPerformed(evt);
            }
        });

        buttonCustomerConcerts.setBackground(new java.awt.Color(255, 255, 255));
        buttonCustomerConcerts.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        buttonCustomerConcerts.setText("Concerts");
        buttonCustomerConcerts.setContentAreaFilled(false);
        buttonCustomerConcerts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCustomerConcerts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerConcertsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonCustomerConcerts, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(buttonBookConceret, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(buttonCustomerView)
                                .addGap(133, 133, 133)
                                .addComponent(buttonCustomerConceret, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(391, 391, 391))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCustomerConceret, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustomerView, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBookConceret, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustomerConcerts, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelCustomer.setBackground(new java.awt.Color(204, 204, 204));
        panelCustomer.setLayout(new java.awt.CardLayout());

        panelcustomerconcert.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel5.setText("AVAILABLE NOW !!");

        javax.swing.GroupLayout panelcustomerconcertLayout = new javax.swing.GroupLayout(panelcustomerconcert);
        panelcustomerconcert.setLayout(panelcustomerconcertLayout);
        panelcustomerconcertLayout.setHorizontalGroup(
            panelcustomerconcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustomerconcertLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(815, Short.MAX_VALUE))
        );
        panelcustomerconcertLayout.setVerticalGroup(
            panelcustomerconcertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustomerconcertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
        );

        panelCustomer.add(panelcustomerconcert, "card2");

        panelcustomerbooking.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("BOOK CONCERT !!");

        javax.swing.GroupLayout panelcustomerbookingLayout = new javax.swing.GroupLayout(panelcustomerbooking);
        panelcustomerbooking.setLayout(panelcustomerbookingLayout);
        panelcustomerbookingLayout.setHorizontalGroup(
            panelcustomerbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustomerbookingLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(803, Short.MAX_VALUE))
        );
        panelcustomerbookingLayout.setVerticalGroup(
            panelcustomerbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustomerbookingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(415, Short.MAX_VALUE))
        );

        panelCustomer.add(panelcustomerbooking, "card3");

        panelcustomeredit.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel8.setText("EDIT DATA !!");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Address");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("E-mail");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Phone No.");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("First Name");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Town");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Post Code");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Last Name");

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Account No.");

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setText("Organization");

        jTextField15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Web Address");

        jTextField16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Gender");

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton3.setText("others");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelcustomereditLayout = new javax.swing.GroupLayout(panelcustomeredit);
        panelcustomeredit.setLayout(panelcustomereditLayout);
        panelcustomereditLayout.setHorizontalGroup(
            panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustomereditLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelcustomereditLayout.createSequentialGroup()
                .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcustomereditLayout.createSequentialGroup()
                        .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelcustomereditLayout.createSequentialGroup()
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelcustomereditLayout.createSequentialGroup()
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel19)
                                    .addGap(40, 40, 40)
                                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(154, Short.MAX_VALUE))
                    .addGroup(panelcustomereditLayout.createSequentialGroup()
                        .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addGroup(panelcustomereditLayout.createSequentialGroup()
                                .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                        .addComponent(jTextField4))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelcustomereditLayout.createSequentialGroup()
                        .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))))
        );
        panelcustomereditLayout.setVerticalGroup(
            panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustomereditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcustomereditLayout.createSequentialGroup()
                        .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcustomereditLayout.createSequentialGroup()
                        .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelcustomereditLayout.createSequentialGroup()
                        .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelcustomereditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelcustomereditLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCustomer.add(panelcustomeredit, "card5");

        panelcustomerview.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel7.setText("VIEW BOOKINGS !!");

        javax.swing.GroupLayout panelcustomerviewLayout = new javax.swing.GroupLayout(panelcustomerview);
        panelcustomerview.setLayout(panelcustomerviewLayout);
        panelcustomerviewLayout.setHorizontalGroup(
            panelcustomerviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustomerviewLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(813, Short.MAX_VALUE))
        );
        panelcustomerviewLayout.setVerticalGroup(
            panelcustomerviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcustomerviewLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        panelCustomer.add(panelcustomerview, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustomerHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCustomerHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 474, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(988, 741));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExitCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitCustomerMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BtnExitCustomerMouseClicked

    private void BtnExitCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitCustomerMouseEntered
        BtnExitCustomer.setBackground( new Color(255,255,255));
    }//GEN-LAST:event_BtnExitCustomerMouseEntered

    private void BtnExitCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitCustomerMouseExited
        BtnExitCustomer.setBackground( new Color(255,255,255));
    }//GEN-LAST:event_BtnExitCustomerMouseExited

    private void ButtonMaximizeCusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMaximizeCusMouseClicked
        if (max){
            CustomerDashboard.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            max =  false;
        }
        else{
            setExtendedState(JFrame.NORMAL);
            max = true;
        }
    }//GEN-LAST:event_ButtonMaximizeCusMouseClicked

    private void ButtonMaximizeCusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMaximizeCusMouseEntered
        ButtonMaximizeCus.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_ButtonMaximizeCusMouseEntered

    private void ButtonMaximizeCusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMaximizeCusMouseExited
        ButtonMaximizeCus.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_ButtonMaximizeCusMouseExited

    private void ButtonMaximizeCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMaximizeCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonMaximizeCusActionPerformed

    private void ButtonMinimizeCusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMinimizeCusMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_ButtonMinimizeCusMouseClicked

    private void ButtonMinimizeCusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMinimizeCusMouseEntered
        ButtonMinimizeCus.setBackground( new Color(255,255,255));
    }//GEN-LAST:event_ButtonMinimizeCusMouseEntered

    private void ButtonMinimizeCusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMinimizeCusMouseExited
        ButtonMinimizeCus.setBackground( new Color(0,0,0));

    }//GEN-LAST:event_ButtonMinimizeCusMouseExited

    private void ButtonMinimizeCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMinimizeCusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonMinimizeCusActionPerformed

    private void buttonCustomerConceretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerConceretActionPerformed
       panelCustomer.removeAll();
       panelCustomer.repaint();
       panelCustomer.revalidate();
       panelCustomer.add(panelcustomeredit);
       panelCustomer.repaint();
       panelCustomer.revalidate();
    }//GEN-LAST:event_buttonCustomerConceretActionPerformed

    private void buttonCustomerViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerViewActionPerformed
       panelCustomer.removeAll();
       panelCustomer.repaint();
       panelCustomer.revalidate();
       panelCustomer.add(panelcustomerview);
       panelCustomer.repaint();
       panelCustomer.revalidate();
    }//GEN-LAST:event_buttonCustomerViewActionPerformed

    private void buttonBookConceretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBookConceretActionPerformed
       panelCustomer.removeAll();
       panelCustomer.repaint();
       panelCustomer.revalidate();
       panelCustomer.add(panelcustomerbooking);
       panelCustomer.repaint();
       panelCustomer.revalidate();
    }//GEN-LAST:event_buttonBookConceretActionPerformed

    private void buttonCustomerConcertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerConcertsActionPerformed
    
       panelCustomer.removeAll();
       panelCustomer.repaint();
       panelCustomer.revalidate();
       panelCustomer.add(panelcustomerconcert);
       panelCustomer.repaint();
       panelCustomer.revalidate();
       
    }//GEN-LAST:event_buttonCustomerConcertsActionPerformed

    private void panelCustomerHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustomerHeaderMouseDragged
    if(max) {
        int x =evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x -xmouse,y -ymouse);
        
        
    }
    }//GEN-LAST:event_panelCustomerHeaderMouseDragged

    private void panelCustomerHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustomerHeaderMousePressed
    xmouse = evt.getX();
    ymouse = evt.getY();
    }//GEN-LAST:event_panelCustomerHeaderMousePressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        admin log = new admin();
        log.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText(null);
        jTextField3.setText(null);

        jTextField4.setText(null);
        jTextField10.setText(null);
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField6.setText(null);
        jTextField3.setText(null);
        jTextField7.setText(null);
        jTextField16.setText(null);
        jTextField14.setText(null);
        jTextField15.setText(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String First_name=jTextField4.getText();
        String Last_name=jTextField10.getText();
        String email=jTextField1.getText();
        String phone_no=jTextField2.getText();
        String address=jTextField6.getText();
        String town=jTextField3.getText();
        String postcode=jTextField7.getText();
        String web_address=jTextField16.getText();
        String ac_no=jTextField14.getText();
        String organization=jTextField15.getText();
        PreparedStatement pst;
        if (First_name.equals("")){
            JOptionPane.showMessageDialog(null,"input firstname");
        }

        else if (Last_name.equals("")){
            JOptionPane.showMessageDialog(null,"input lastname");
        }

        else if (email.equals("")){
            JOptionPane.showMessageDialog(null,"input email");
        }

        else if (phone_no.equals("")){
            JOptionPane.showMessageDialog(null,"input phone no");
        }
                
                
        else if (address.equals("")){
            JOptionPane.showMessageDialog(null,"input address");
        }
        else if (postcode.equals("")){
            JOptionPane.showMessageDialog(null,"input postcode");
        }

        try{
            String sql="INSERT INTO user_info(First_Name,Last_Name,Gender,phone_no,Account_No,Post_code,Organization_Name,Web_address,Address,Town) VALUES(?,?,?,?,?,?,?,?,?,?) ";
          //String sql="UPDATE user_info First_Name=?,Last_Name=?,Gender=?,phone_no=?,Account_No=?,Post_code=?,Organization_Name=?,Web_address=?,Address=?,where Town=?";
            
            pst=jdbc.getConnection().prepareStatement(sql);
            
            pst.setString(1, First_name);
            pst.setString(2, Last_name);
            pst.setString(3, gender);
            pst.setInt(4, Integer.parseInt(phone_no));
            pst.setString(5, ac_no);
            pst.setInt(6, Integer.parseInt(postcode));
            pst.setString(7, organization);
            pst.setString(8, web_address);
            pst.setString(9, address);
            pst.setString(10, town);
            
            boolean execute = pst.execute();
            JOptionPane.showMessageDialog(this, "insertion successfull");
          
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"please fill every given field");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
       if(jRadioButton2.isSelected())
            jRadioButton1.setSelected(false);
            jRadioButton3.setSelected(false);
            gender="Female";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected())
            jRadioButton2.setSelected(false);
            jRadioButton3.setSelected(false);
            gender="male";
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        if(jRadioButton3.isSelected())
            jRadioButton2.setSelected(false);
            jRadioButton1.setSelected(false);
            gender="others";
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        StudentEntity student = new StudentEntity();
        String First_name=jTextField4.getText();
        String Last_name=jTextField10.getText();
        String email=jTextField1.getText();
        String phone_no=jTextField2.getText();
        String address=jTextField6.getText();
        String town=jTextField3.getText();
        String postcode=jTextField7.getText();
        String web_address=jTextField16.getText();
        String ac_no=jTextField14.getText();
        String organization=jTextField15.getText();
        PreparedStatement pst;
           try{
            String sqll="update user_info set First_Name=?,Last_Name=?,Gender=?,phone_no=?,Account_No=?,Post_code=?,Organization_Name=?,Web_address=?,Address=?,Town=? where userid=?";
            pst=jdbc.getConnection().prepareStatement(sqll);
            
            
            System.out.println(phone_no);
            pst.setString(1, First_name);
            pst.setString(2, Last_name);
            pst.setString(3, gender);
            //System.out.println(uid);
            pst.setInt(4, 78878998);
            System.out.println(uid);
            
            pst.setInt(5, Integer.parseInt(ac_no));
            
            pst.setInt(6, Integer.parseInt(postcode));
            
            pst.setString(7, organization);
            pst.setString(8, web_address);
            pst.setString(9, address);
            pst.setString(10, town);
             
            pst.setInt(11, uid);
            
            boolean execute = pst.execute();
            JOptionPane.showMessageDialog(this, "insertion successfull");
           }
            catch(Exception e){
            JOptionPane.showMessageDialog(this,"please fill every given field");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExitCustomer;
    private javax.swing.JButton ButtonMaximizeCus;
    private javax.swing.JButton ButtonMinimizeCus;
    private javax.swing.JButton buttonBookConceret;
    private javax.swing.JButton buttonCustomerConceret;
    private javax.swing.JButton buttonCustomerConcerts;
    private javax.swing.JButton buttonCustomerView;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel panelCustomer;
    private java.awt.Panel panelCustomerHeader;
    private javax.swing.JPanel panelcustomerbooking;
    private javax.swing.JPanel panelcustomerconcert;
    private javax.swing.JPanel panelcustomeredit;
    private javax.swing.JPanel panelcustomerview;
    // End of variables declaration//GEN-END:variables
private String gender;

}
